[tool.importlinter]
root_package = "src"

[[tool.importlinter.contracts]]
id = "application_no_interfaces"
name = "Application 不能依赖 Interface"
type = "forbidden"
source_modules = ["src.application"]
forbidden_modules = ["src.interfaces"]

[[tool.importlinter.contracts]]
id = "domain_no_interfaces"
name = "Domain 不能依赖 Interface"
type = "forbidden"
source_modules = ["src.domain"]
forbidden_modules = ["src.interfaces"]

[[tool.importlinter.contracts]]
id = "domain_no_infrastructure"
name = "Domain 不能依赖 Infrastructure"
type = "forbidden"
source_modules = ["src.domain"]
forbidden_modules = ["src.infrastructure"]

[[tool.importlinter.contracts]]
id = "domain_no_application"
name = "Domain 不能依赖 Application"
type = "forbidden"
source_modules = ["src.domain"]
forbidden_modules = ["src.application"]
